version: '3'
services:
  website:
    container_name: 'website'
    image: '${WEBSITE_IMAGE}'
    ports:
      - '3000:3000'
    volumes:
      - website:/website/build/

  nginx:
    container_name: 'nginx'
    image: '${NGINX_IMAGE}'
    ports:
      - '8080:8080'
    volumes:
      - website:/usr/share/nginx/html/website
    restart: always  # Add this line to specify the restart policy

volumes:
  website:
